/* Author-only editing within the existing Create Games screen. Local save is not publishing. */
(()=>{
 'use strict';
 const M=window.InterviewModel,store=()=>InterviewStore.create(localStorage),esc=escapeHtml;
 const root=document.getElementById('createInterview');let editing=null,updatePreview=()=>{};
 const field=(name,id,max,value='')=>`<label class="interview-field">${name}<input id="${id}" maxlength="${max}" value="${esc(value)}"></label>`;
 function status(message){root.querySelector('[role=status]').textContent=message;}
 function units(){const rows=[...document.querySelectorAll('[name=creatorAssignedUnit]')].map(e=>({value:e.value,label:e.parentElement.textContent}));
 const senior={nh5:['Hello, friends!','Happy birthday!','Can you play dodgeball?','Who is this?','Let’s go to the zoo.','At a restaurant.','Welcome to Japan!','Who is your hero?'],nh6:['This is me!','My Daily Schedule','My Weekend','Let’s see the world.','Where is it from?','Save the animals.','My Best Memory','My Future, My Dream']};
 Object.entries(senior).forEach(([b,titles])=>titles.forEach((title,i)=>rows.push({value:b+':'+(i+1),label:'NEW HORIZON '+b.slice(-1)+' Unit '+(i+1)+' — '+title})));return rows;
 }
 function answers(values){const box=root.querySelector('#interviewAnswers');box.replaceChildren();values.forEach((a,i)=>{
  const row=document.createElement('div');row.className='interview-row';row.dataset.answerId=a.id;
  row.innerHTML=`<label>回答名 ${i+1}<input maxlength="40" value="${esc(a.label)}"></label><button type="button" aria-label="回答 ${i+1}を上へ">↑</button><button type="button" aria-label="回答 ${i+1}を削除">削除</button>`;
  row.querySelectorAll('button')[0].onclick=()=>{const all=readAnswers();if(i>0){[all[i-1],all[i]]=[all[i],all[i-1]];answers(all);}};
  row.querySelectorAll('button')[1].onclick=()=>answers(readAnswers().filter(x=>x.id!==a.id));box.append(row);
 });}
 function readAnswers(){return [...root.querySelectorAll('#interviewAnswers .interview-row')].map((e,i)=>({id:e.dataset.answerId,label:e.querySelector('input').value,order:i}));}
 function readSentences(){return [...root.querySelectorAll('[data-sentence-input]')].map(e=>e.value);}
 function sentences(values){const box=root.querySelector('#interviewSentences');box.replaceChildren();values.forEach((value,i)=>{const row=document.createElement('div');row.className='interview-row';row.innerHTML=`<label class="interview-field">${i+1}文目<input data-sentence-input ${i===0?'id="interviewQuestion"':''} maxlength="200" value="${esc(value)}"></label><button type="button" aria-label="${i+1}文目を削除" ${values.length===1?'disabled':''}>−</button>`;row.querySelector('button').onclick=()=>sentences(readSentences().filter((_,n)=>n!==i));box.append(row);});}
 function open(id){try{editing=id?store().listPresets().find(p=>p.id===id):null;if(id&&!editing)throw Error('プリセットが見つかりません');
  root.innerHTML='<div class="head"><button type="button" aria-label="戻る" id="interviewAuthorBack">戻る</button><h1>Interviewを作る</h1></div><p>このブラウザに保存</p><p>本ページへの公開は別途依頼してください。端末間では自動同期されません。</p><div class="interview-form">'+
   '<button type="button" id="interviewColors">Colorsサンプルを作成</button>'+field('タイトル','interviewTitle',80,editing?.title||'INTERVIEW')+field('説明','interviewDescription',500,editing?.description)+'<section><h2>質問文</h2><div id="interviewSentences"></div><button type="button" id="interviewAddSentence" aria-label="文を追加">＋</button><small>1つの欄に1文を入力します。全体で200文字以内です。</small></section>'+
   '<small>同じ (P) はすべて同じカードになります。別々に選ぶ場合は (P1)、(P2) を使います（最大9枠）。固定文も使えます。</small><section><h2>Picture Cards</h2><p id="interviewCardCount"></p><div id="interviewCards"></div></section><section><h2>回答エリア</h2><div id="interviewAnswers"></div><button type="button" id="interviewAddAnswer">回答エリアを追加</button></section><section><h2>割り当てるUnit（Activitiesに表示）</h2><div class="interview-units">'+units().map(u=>`<label><input type="checkbox" name="interviewUnit" value="${u.value}">${esc(u.label)}</label>`).join('')+'</div></section><div class="interview-actions"><button type="button" id="interviewSave">プリセットを保存</button></div><p role="status" aria-live="polite"></p></div>';
  const heading=root.querySelector('.head');heading.classList.add('activity-compact-heading');const notes=[...root.querySelectorAll(':scope>p')],note=document.createElement('p');note.className='interview-author-note';note.textContent=notes.map(e=>e.textContent).join(' ／ ');notes.forEach(e=>e.remove());heading.append(note);
  const unitBox=root.querySelector('.interview-units'),bookNames={lt1:"Let's Try 1",lt2:"Let's Try 2",nh5:'New Horizon 5',nh6:'New Horizon 6'};
  const unitLabels=[...unitBox.children];unitBox.replaceChildren();for(const [book,title] of Object.entries(bookNames)){const section=document.createElement('details');section.dataset.unitBook=book;const summary=document.createElement('summary');summary.textContent=title;section.append(summary);unitLabels.filter(e=>e.querySelector('input').value.startsWith(book+':')).forEach(e=>{const input=e.querySelector('input'),n=input.value.split(':')[1];e.lastChild.textContent=e.textContent.replace(/^.*?Unit\s*\d+\s*(?:—\s*)?/,'Unit '+n+'　');section.append(e);});unitBox.append(section);}
  const form=root.querySelector('.interview-form');
  root.querySelector('#interviewTitle').parentElement.firstChild.textContent='活動タイトル（教師・児童に表示）';
  root.querySelector('#interviewDescription').parentElement.firstChild.textContent='教師用メモ（児童には表示しません）';
  root.querySelector('#interviewDescription').parentElement.insertAdjacentHTML('beforebegin',field('児童への説明（文章作り画面に表示）','interviewStudentInstructions',500,editing?.studentInstructions||''));
  const layout=document.createElement('div');layout.className='interview-editor-layout';form.before(layout);layout.append(form);
  layout.insertAdjacentHTML('beforeend','<section class="interview-preview-panel"><div class="interview-preview-toolbar"><strong>プレビュー</strong><div role="group" aria-label="プレビュー画面"><button type="button" data-preview-tab="teacher" aria-pressed="true">教師用</button><button type="button" data-preview-tab="compose" aria-pressed="false">児童用：文章作り</button><button type="button" data-preview-tab="sheet" aria-pressed="false">児童用：インタビュー</button></div><div role="group" aria-label="画面の向き"><button type="button" data-preview-orientation="landscape" aria-pressed="true">横画面</button><button type="button" data-preview-orientation="portrait" aria-pressed="false">縦画面</button></div><small>仮の番号35人で試せます。実際の名簿・回答は変更されません。</small><p id="interviewPreviewStatus" role="note"></p></div><div class="interview-preview-viewport"><div class="interview-preview-device"><iframe id="interviewPreview" title="活動のプレビュー"></iframe></div></div></section>');
  const selected=new Set(editing?.cardIds||[]),groups=new Map();rouletteAvailableCards().forEach(c=>{if(!groups.has(c.category))groups.set(c.category,[]);groups.get(c.category).push(c);});
  sentences(M.sentenceTemplates(editing?.question.template||'Do you like (P)?'));
  root.querySelector('#interviewAddSentence').onclick=()=>{sentences([...readSentences(),'']);[...root.querySelectorAll('[data-sentence-input]')].at(-1).focus();};
  root.querySelector('#interviewCards').innerHTML=[...groups].map(([category,cards])=>`<details data-card-category="${esc(category)}"><summary><input type="checkbox" class="interview-category-toggle" data-category-toggle="${esc(category)}" aria-label="${esc(categoryLabel(category))}をまとめて選択・解除"><span>${esc(categoryLabel(category))}（${cards.length}）</span></summary><div class="interview-options">${cards.map(c=>`<button type="button" class="interview-chip" data-card-id="${esc(c.id)}" aria-pressed="${selected.has(c.id)}">${esc(c.english)}</button>`).join('')}</div></details>`).join('');
  function count(){root.querySelector('#interviewCardCount').textContent=selected.size+'枚を選択中';root.querySelectorAll('[data-card-id]').forEach(e=>e.setAttribute('aria-pressed',String(selected.has(e.dataset.cardId))));root.querySelectorAll('[data-category-toggle]').forEach(e=>{const list=groups.get(e.dataset.categoryToggle),n=list.filter(c=>selected.has(c.id)).length;e.checked=n===list.length;e.indeterminate=n>0&&n<list.length;});}count();
  root.querySelectorAll('[data-card-id]').forEach(e=>e.onclick=()=>{const id=e.dataset.cardId;selected.has(id)?selected.delete(id):selected.add(id);count();});
  root.querySelectorAll('[data-category-toggle]').forEach(e=>e.onclick=event=>{event.stopPropagation();const list=groups.get(e.dataset.categoryToggle),all=list.every(c=>selected.has(c.id));list.forEach(c=>all?selected.delete(c.id):selected.add(c.id));count();syncTiers();updatePreview();});
  root.querySelectorAll('[data-card-category]').forEach(group=>{const list=groups.get(group.dataset.cardCategory),box=group.querySelector('.interview-options');box.replaceChildren();for(const tier of ['standard','plus','lets-try']){const rows=list.filter(c=>c.displayGroup===tier);if(!rows.length)continue;const section=document.createElement('div');section.className='interview-tier';section.dataset.cardTier=tier;section.innerHTML=`<label><input type="checkbox" aria-label="${esc(categoryLabel(group.dataset.cardCategory))} ${tier==='standard'?'スタンダード':tier==='plus'?'プラス':'Let’s Try! 追加語'}を一括選択"><span>${tier==='standard'?'スタンダード':tier==='plus'?'プラス':'Let’s Try! 追加語'}（${rows.length}）</span></label><div class="interview-tier-chips"></div>`;for(const c of rows){const b=document.createElement('button');b.type='button';b.className='interview-chip';b.dataset.cardId=c.id;b.textContent=c.english;b.setAttribute('aria-pressed',String(selected.has(c.id)));b.onclick=()=>{selected.has(c.id)?selected.delete(c.id):selected.add(c.id);count();syncTiers();updatePreview();};section.lastElementChild.append(b);}section.querySelector('input').onchange=e=>{rows.forEach(c=>e.target.checked?selected.add(c.id):selected.delete(c.id));count();syncTiers();updatePreview();};box.append(section);}});
  function syncTiers(){root.querySelectorAll('[data-card-tier]').forEach(section=>{const ids=[...section.querySelectorAll('[data-card-id]')].map(b=>b.dataset.cardId),n=ids.filter(id=>selected.has(id)).length,input=section.querySelector('input');input.checked=n===ids.length;input.indeterminate=n>0&&n<ids.length;});}syncTiers();
  root.querySelectorAll('[name=interviewUnit]').forEach(e=>{e.checked=!!editing?.assignedUnits.some(u=>e.value===u.bookId+':'+u.unit);});
  answers(editing?.answerAreas||[{id:M.newId('answer'),label:'YES',order:0},{id:M.newId('answer'),label:'NO',order:1}]);
  root.querySelector('#interviewAuthorBack').onclick=async()=>{if(document.fullscreenElement)await document.exitFullscreen();else{renderLibrary();show('createActivities');}};
  root.querySelector('#interviewAddAnswer').onclick=()=>{const a=readAnswers();if(a.length>=12)return status('回答エリアは12個までです');answers([...a,{id:M.newId('answer'),label:'',order:a.length}]);};
  root.querySelector('#interviewColors').onclick=()=>{try{
   const words=['red','blue','green','yellow','pink','orange','purple','black','white'];const ids=words.map(w=>{const matches=rouletteAvailableCards().filter(c=>c.category==='colors'&&c.english===w);if(matches.length!==1)throw Error('カードを確認してください: '+w);return matches[0].id;});
   editing=null;root.querySelector('#interviewTitle').value='INTERVIEW';root.querySelector('#interviewDescription').value='色について友達に質問しよう';sentences(['Do you like (P)?']);
   root.querySelector('#interviewStudentInstructions').value='色について友達に質問しよう';root.querySelector('#interviewDescription').value='';
   selected.clear();ids.forEach(id=>selected.add(id));root.querySelectorAll('[name=interviewUnit]').forEach(e=>e.checked=e.value==='lt1:4');
   answers([{id:M.newId('answer'),label:'YES',order:0},{id:M.newId('answer'),label:'NO',order:1}]);count();status('9色・Let’s Try 1 Unit 4を設定しました。確認して保存してください。');
  }catch(e){status(e.message);}};
  root.querySelector('#interviewSave').onclick=()=>{try{
   const now=new Date().toISOString(),cardIds=rouletteAvailableCards().filter(c=>selected.has(c.id)).map(c=>c.id),template=readSentences().flatMap(M.sentenceTemplates).join('\n');
   const value={version:2,type:'interview',id:editing?.id||M.newId(),name:root.querySelector('#interviewTitle').value,title:root.querySelector('#interviewTitle').value,description:root.querySelector('#interviewDescription').value,assignedUnits:[...root.querySelectorAll('[name=interviewUnit]:checked')].map(e=>{const [bookId,n]=e.value.split(':');return {bookId,unit:Number(n)};}),question:{template,slots:M.slotIds(template).map(id=>({id,type:'picture-card',cardIds}))},cardIds,answerAreas:readAnswers(),createdAt:editing?.createdAt||now,updatedAt:now};
   value.studentInstructions=root.querySelector('#interviewStudentInstructions').value;
   store().savePreset(M.validatePreset(value,new Set(rouletteAvailableCards().map(c=>c.id))));renderLibrary();show('createActivities');
  }catch(e){status(e.message);}};
  const frame=root.querySelector('#interviewPreview');let tab='teacher',orientation='landscape',previewTimer;
  function draft(){const now=new Date().toISOString(),cardIds=rouletteAvailableCards().filter(c=>selected.has(c.id)).map(c=>c.id),template=readSentences().flatMap(M.sentenceTemplates).join('\n');return {version:2,type:'interview',id:editing?.id||'preview-draft',name:root.querySelector('#interviewTitle').value||'未命名の活動',title:root.querySelector('#interviewTitle').value||'INTERVIEW',description:root.querySelector('#interviewDescription').value,studentInstructions:root.querySelector('#interviewStudentInstructions').value,assignedUnits:[],question:{template,slots:M.slotIds(template).map(id=>({id,type:'picture-card',cardIds}))},cardIds,answerAreas:readAnswers(),createdAt:editing?.createdAt||now,updatedAt:now};}
  updatePreview=()=>{clearTimeout(previewTimer);previewTimer=setTimeout(()=>{if(!frame.isConnected||!frame.contentWindow||!root.classList.contains('active'))return;try{const preset=M.validatePreset(draft());root.querySelector('#interviewPreviewStatus').textContent='';frame.hidden=false;frame.contentWindow.postMessage({type:'interview-author-preview',preset,phase:tab},location.protocol==='file:'?'*':location.origin);}catch(e){frame.hidden=true;root.querySelector('#interviewPreviewStatus').textContent='プレビュー：'+e.message;}},120);};
  function resize(){if(innerWidth>900)layout.style.height=Math.max(350,innerHeight-layout.getBoundingClientRect().top-16)+'px';else layout.style.height='auto';const viewport=root.querySelector('.interview-preview-viewport'),device=root.querySelector('.interview-preview-device'),w=orientation==='portrait'?768:1180,h=orientation==='portrait'?1024:760,scale=Math.max(.1,Math.min(viewport.clientWidth/w,viewport.clientHeight/h));device.style.width=w+'px';device.style.height=h+'px';device.style.left=Math.max(0,(viewport.clientWidth-w*scale)/2)+'px';device.style.transform=`scale(${scale})`;}
  function changeTab(){root.querySelectorAll('[data-preview-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.previewTab===tab)));frame.src='../grade34/'+(tab==='teacher'?'interview.html':'interview-receive.html')+'?authorPreview=1';}
  frame.onload=updatePreview;root.querySelectorAll('[data-preview-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.previewTab;changeTab();});root.querySelectorAll('[data-preview-orientation]').forEach(b=>b.onclick=()=>{orientation=b.dataset.previewOrientation;root.querySelectorAll('[data-preview-orientation]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));resize();});
  root.oninput=updatePreview;root.onchange=updatePreview;root.onclick=null;form.onclick=()=>{syncTiers();updatePreview();};
  window.interviewPreviewResize?.disconnect();window.interviewPreviewResize=new ResizeObserver(resize);window.interviewPreviewResize.observe(root.querySelector('.interview-preview-viewport'));
  if(window.interviewPreviewWindowResize)removeEventListener('resize',window.interviewPreviewWindowResize);window.interviewPreviewWindowResize=resize;addEventListener('resize',resize);
  show('createInterview');changeTab();resize();
 }catch(e){document.getElementById('interviewLibrary').textContent=e.message;show('createActivities');}}
 function renderLibrary(){const library=document.getElementById('interviewLibrary');library.replaceChildren();try{const all=store().listPresets();if(!all.length){library.textContent='保存したInterviewはありません。';return;}
  all.forEach(p=>{const article=document.createElement('article');article.className='created-game-card interview-saved-card activity-blue-tile';const allUnits=units(),assigned=p.assignedUnits.map(u=>allUnits.find(x=>x.value===u.bookId+':'+u.unit)?.label.replace(/(Unit\s*\d+)(?=\S)/,'$1 ')||u.bookId+' Unit '+u.unit).join(' / '),cardMap=new Map(rouletteAvailableCards().map(c=>[c.id,c]));const choices=p.question.slots.map(slot=>{const grouped=new Map();slot.cardIds.forEach(id=>{const c=cardMap.get(id);if(!c)return;const key=categoryLabel(c.category);if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(c.english);});return '('+slot.id+') '+[...grouped].map(([category,words])=>category+' ('+words.join(', ')+')').join(' / ');}).join('\n');article.innerHTML=`<div class="interview-saved-heading"><strong>${esc(assigned||'Unit未指定')}</strong><span>${esc(p.title)}</span></div><div class="interview-saved-info"><p class="interview-saved-question">${esc(M.sentenceTemplates(p.question.template).join(' / '))}</p><p class="interview-saved-choices">${esc(choices)}</p></div><div class="interview-saved-actions"><button type="button" data-edit>編集</button><button type="button" data-delete>削除</button><a href="../grade34/interview.html?preset=${encodeURIComponent(p.id)}&source=local">教師画面で試す</a><button type="button" data-download>設定ファイルDL</button></div>`;
   article.querySelector('[data-edit]').onclick=()=>open(p.id);article.querySelector('[data-download]').onclick=()=>{const clean=M.validatePreset(p),url=URL.createObjectURL(new Blob([JSON.stringify(clean,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=p.id+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};article.querySelector('[data-delete]').onclick=()=>{if(!confirm('このプリセットを削除しますか？'))return;try{store().deletePreset(p.id);renderLibrary();}catch(e){const error=document.createElement('p');error.setAttribute('role','status');error.textContent=e.message;article.append(error);}};library.append(article);
  });
 }catch(e){library.textContent=e.message;}}
 document.getElementById('openInterviewCreator').onclick=()=>open();
 window.InterviewCreator={open,renderLibrary};renderLibrary();
})();
