(()=>{'use strict';
 const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const info=$('#country-info'),map=$('#map'),status=$('#map-status');let svg,view=[0,0,1200,600],selected,drag;
 const ready=window.WorldCountries&&window.WorldSearch&&window.WorldImports&&window.DEKIRU_DATA&&window.CardSet;
 $('#back').addEventListener('click',()=>{try{sessionStorage.setItem('dekiru:nhe-return-activities','nh6:5');}catch{}if(window.speechSynthesis)window.speechSynthesis.cancel();});
 function error(){status.innerHTML='地図やデータを読み込めませんでした。 <button id="retry">再読み込み</button>';$('#retry').onclick=()=>location.reload();}
 if(!ready){error();$('#country-search').disabled=true;return;}
 const countries=new Map(WorldCountries.map(c=>[c.id,c])),cards=new Map(DEKIRU_DATA.cards.map(c=>[c.id,c]));
 function setView(next){const w=Math.min(1200,Math.max(120,next[2])),h=w/2;view=[Math.max(0,Math.min(1200-w,next[0])),Math.max(0,Math.min(600-h,next[1])),w,h];if(svg)svg.setAttribute('viewBox',view.join(' '));if(svg){const marker=$('#map-marker');if(marker)marker.setAttribute('r',Math.max(2,w/180));}}
 function zoom(factor){const w=view[2]*factor;setView([view[0]+(view[2]-w)/2,view[1]+(view[3]-w/2)/2,w,w/2]);}
 $('#zoom-in').onclick=()=>zoom(.7);$('#zoom-out').onclick=()=>zoom(1/.7);$('#reset-map').onclick=()=>setView([0,0,1200,600]);
 function showResults(){const q=$('#country-search').value,list=WorldSearch.find(q);$('#results').replaceChildren();if(!q.trim())return;if(!list.length){$('#results').textContent='国が見つかりません。別の名前で試してください。';return;}list.forEach(c=>{const b=document.createElement('button');b.textContent=c.ja+' / '+c.en;b.onclick=()=>select(c);$('#results').append(b);});}
 $('#country-search').oninput=showResults;$('#search-form').onsubmit=e=>{e.preventDefault();showResults();$('#results button')?.focus();};
 function evidence(e){return `<details class="evidence"><summary>出典・年：${e.year}年</summary><p>${esc(e.title)} / ${esc(e.releaseStatus)}</p><p>${esc(e.classification)}。${esc(e.selectionBasis)}</p><p>確認日：${esc(e.checkedAt)}</p><a href="${esc(e.url)}" target="_blank" rel="noopener">統計の原表を開く</a></details>`;}
 function select(c){selected=c;map.querySelectorAll('[aria-pressed=true]').forEach(el=>el.setAttribute('aria-pressed','false'));const shape=document.getElementById(c.mapId);shape?.setAttribute('aria-pressed','true');const marker=$('#map-marker');if(marker){marker.setAttribute('cx',c.anchor[0]);marker.setAttribute('cy',c.anchor[1]);marker.setAttribute('visibility','visible');}setView([c.anchor[0]-view[2]/2,c.anchor[1]-view[3]/2,view[2],view[3]]);status.textContent=c.ja+' の場所を表示しています。';
  const d=WorldImports.get(c.id);let body='';
  if(d.status==='domestic')body='<p class="notice">日本は国内です。この画面では、ほかの国から日本への輸入を調べます。</p>';
  else if(d.status==='unresearched')body='<p class="notice">この国の輸入情報は未収録です。「輸入されていない」という意味ではありません。</p>';
  else body='<p class="country-intro">この国から日本へ輸入されているもの（2025年）</p><h3>カードで学べる輸入品</h3><p class="notice">確認できた品目の例です。輸入量のランキングではありません。絵は学習カードです。</p><div class="import-grid">'+d.cards.map(item=>{const card=cards.get(item.cardId);return `<article class="import-card"><img src="${esc(CardSet.source(card))}" alt="${esc(card.japanese)}" loading="lazy"><strong>${esc(card.japanese)}</strong><span class="en">${esc(card.english)}</span><p>${esc(item.note)}</p>${evidence(item.evidence)}</article>`;}).join('')+'</div><p class="notice">表示のないカードは、この品目の情報は未収録です。輸入の有無を示すものではありません。</p><h3>主な輸入品（大きな分類）</h3>'+d.other.map(item=>`<article class="broad-item"><strong>${esc(item.ja)}</strong><p>${esc(item.note)}</p>${evidence(item.evidence)}</article>`).join('');
  info.innerHTML=`<div class="country-title"><h2>${esc(c.ja)}</h2><button id="say-country" aria-label="英語名を聞く">🔊</button></div><p class="country-en">${esc(c.en)}</p><p class="speech-note" id="speech-status"></p>${body}`;
  const say=$('#say-country');if(!window.speechSynthesis||!window.SpeechSynthesisUtterance){say.disabled=true;$('#speech-status').textContent='このブラウザーでは音声を再生できません。';}else say.onclick=()=>{const u=new SpeechSynthesisUtterance(c.en);u.lang='en-US';u.rate=.8;u.onerror=()=>{$('#speech-status').textContent='音声を再生できませんでした。端末の音声設定をご確認ください。';};speechSynthesis.cancel();speechSynthesis.speak(u);};
 }
 map.addEventListener('pointerdown',e=>{if(!svg||e.button!==0)return;drag={x:e.clientX,y:e.clientY,view:[...view],target:e.target.closest('[id^=country-]'),moved:false};map.setPointerCapture(e.pointerId);map.classList.add('dragging');});
 map.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>5)drag.moved=true;if(drag.moved){const r=map.getBoundingClientRect();setView([drag.view[0]-dx/r.width*drag.view[2],drag.view[1]-dy/r.height*drag.view[3],drag.view[2],drag.view[3]]);}});
 map.addEventListener('pointerup',()=>{if(drag&&!drag.moved&&drag.target){const c=countries.get(drag.target.id.slice(8));if(c)select(c);}drag=null;map.classList.remove('dragging');});map.addEventListener('pointercancel',()=>{drag=null;map.classList.remove('dragging');});
 map.onkeydown=e=>{const delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(delta){e.preventDefault();setView([view[0]+delta[0]*view[2]/10,view[1]+delta[1]*view[3]/10,view[2],view[3]]);}};
 const full=$('#fullscreen');function fullState(on){document.body.classList.toggle('expanded',on);full.setAttribute('aria-pressed',String(on));full.textContent=on?'全画面を解除':'全画面表示';}
 full.onclick=async()=>{if(full.getAttribute('aria-pressed')==='true'){if(document.fullscreenElement)await document.exitFullscreen();fullState(false);}else{fullState(true);try{await $('#world-activity').requestFullscreen?.();}catch{}}};document.addEventListener('fullscreenchange',()=>fullState(!!document.fullscreenElement));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.fullscreenElement)fullState(false);});
 fetch('assets/world-map.svg').then(r=>{if(!r.ok)throw Error();return r.text();}).then(text=>{const doc=new DOMParser().parseFromString(text,'image/svg+xml');if(doc.querySelector('parsererror')||doc.documentElement.tagName!=='svg')throw Error();svg=document.importNode(doc.documentElement,true);map.replaceChildren(svg);svg.removeAttribute('width');svg.removeAttribute('height');svg.setAttribute('aria-label','世界地図');const marker=document.createElementNS('http://www.w3.org/2000/svg','circle');marker.id='map-marker';marker.setAttribute('visibility','hidden');svg.append(marker);WorldCountries.forEach(c=>{const shape=document.getElementById(c.mapId);if(shape){shape.setAttribute('aria-label',c.ja);shape.setAttribute('aria-pressed','false');}});setView(view);status.textContent='国名を検索するか、地図の国をタップしてください。';if(selected)select(selected);}).catch(error);
})();
